### ISSUE TITLE
On neovim, can't get to work with only vim-dispatch-neovim

### ISSUE THREAD

**Issue by ghost** [clojure-vim/vim-jack-in#6]
When I install only vim-dispatch-neovim with vim-jack-in, it raises an error on :Lein command.

```vim
Plug 'clojure-vim/vim-jack-in'
Plug 'radenling/vim-dispatch-neovim'
```

![Screen Shot 2020-09-15 at 19 30 52](https://user-images.githubusercontent.com/69860869/93271554-f9b21800-f789-11ea-9e18-282c1553ce5f.png)

When install vim-dispatch with vim-jack-in, it opens a new tmux window and runs the process, it's good but not the ideal because i want to run all inside neovim.

```vim
Plug 'clojure-vim/vim-jack-in'
Plug 'tpope/vim-dispatch'
```

![Screen Shot 2020-09-15 at 19 33 29](https://user-images.githubusercontent.com/69860869/93271725-57466480-f78a-11ea-95c2-286fcd5556e7.png)

When I install vim-dispatch, vim-jack-in and vim-dispatch-neovim, it opens a new tab with the process

```vim
Plug 'clojure-vim/vim-jack-in'
Plug 'tpope/vim-dispatch'
Plug 'radenling/vim-dispatch-neovim'
```

![Screen Shot 2020-09-15 at 19 35 25](https://user-images.githubusercontent.com/69860869/93271843-9c6a9680-f78a-11ea-962f-533b2f294eb9.png)

I feel like this a quite strange behavior, it's correct?

**Comment by SevereOverfl0w** [comment]
It's correct. Vim-dispatch-neovim is an extension for vim-dispatch to allow opening processes with :terminal.

Vim-dispatch is required, vim-dispatch-neovim is not.
